### ISSUE TITLE
From-Until Feature 

### ISSUE THREAD

**Issue by krawez** [mathsdada/Facebook-Page-Scraper#2]
Is it possible to implement a feature to limit the number of posts from a page being scraped? For example, by date or just simply by number? 

I am struggling to implement it myself and collecting ALL the posts from big pages like cnn will take ages...

**Comment by mathsdada** [comment]
Yes that can be done. If you could do it yourself then please raise a pull request. I'll review it. If you can't do it then I'll work on it on coming Monday.

**Comment by krawez** [comment]
Thank you! I am working on it, but it doesn’t work yet. Now I am trying to implement something that will take all the comments and replies from only one fb post based on your code, but got stuck... I will make a pull request to show how far I got. Would be super grateful if you could review it.

Cheers, Dasha

Am 22.08.2018 um 18:25 schrieb Gangadhar Vukkesala <notifications@github.com<mailto:notifications@github.com>>:


Yes that can be done. If you could do it yourself then please raise a pull request. I'll review it. If you can't do it then I'll work on it on coming Monday.

**Comment by mathsdada** [comment]
Sure. Raise a pull request once changes are done..I'll review it.

**Comment by mathsdada** [comment]
Closing this as I did not receive any pull request from you. Re-open this when you are ready with the change.
