### ISSUE TITLE
Scraping the Info & Ads Section

### ISSUE THREAD

**Issue by bizfreak22** [mathsdada/Facebook-Page-Scraper#3]
Hello, great scraper, works very well! Just wanted to ask if it was possible for you to add the capability of scraping the Info & Ads Section of the Fan Page? Thank you for your time!

**Comment by mathsdada** [comment]
Could you please elaborate you requirement?

**Comment by bizfreak22** [comment]
Recently Facebook added a section to every Fan page called Info & Ads that displays what Ads the Fan Page is currently running. I was wondering if its possible to somehow scrape that data as well. 

The data collected would be essentially the same, the post id, country in which the active ad is displaying, etc.

Here are some screenshots. Thanks a lot for your time! Your script is really incredible btw, works exceptionally well.

<img width="209" alt="screen shot 2018-09-10 at 10 39 30 pm" src="https://user-images.githubusercontent.com/33889841/45334910-e2147900-b54a-11e8-9633-c0d5837b5d07.png">

<img width="1093" alt="screen shot 2018-09-10 at 10 44 44 pm" src="https://user-images.githubusercontent.com/33889841/45335062-9c0be500-b54b-11e8-9d87-bd563b63b9a0.png">

**Comment by mathsdada** [comment]
I am not actively working on this project. Please raise a pull request if you could make code changes for this. I will review the changes when you raise a pull request.

**Comment by mathsdada** [comment]
Closing this issue as there is no update on pull request
